transports:
  pgProtocol:
    secure: false
    enable: false
  nativeProtocol:
    secure: false
    enable: false
  grpc:
    bindAddress: "0.0.0.0"
    portNumber: 55051
    secure: false
    enable: true
vdb:
  descriptorBundle: {{ DESCRIPTOR_BUNDLE }}

propertiesFilePath: {{ PROPS_FILE }}

buffer:
  useDisk: false
  encrypt: false
