slice_name: k8s.hpa.overview
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 10__table
  viz_type: table
  query_mode: raw
  groupby: []
  time_grain_sqla: null
  temporal_columns_lookup: {}
  metrics: []
  all_columns:
  - clusterName
  - namespace
  - hpa_name
  - min_replicas
  - max_replicas
  - current_replicas
  - desired_replicas
  - latest_transition_time
  - condition_type
  - condition_status
  - condition_message
  - condition_reason
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: false
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":10,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["clusterName","namespace","hpa_name","min_replicas","max_replicas","current_replicas","desired_replicas","latest_transition_time","condition_type","condition_status","condition_message","condition_reason"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"10__table","viz_type":"table","query_mode":"raw","groupby":[],"time_grain_sqla":null,"temporal_columns_lookup":{},"metrics":[],"all_columns":["clusterName","namespace","hpa_name","min_replicas","max_replicas","current_replicas","desired_replicas","latest_transition_time","condition_type","condition_status","condition_message","condition_reason"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":false,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 82b4e3cd-fa9d-4e68-b7bb-c0ae85e5632b
version: 1.0.0
dataset_uuid: 0697465d-6b42-46f8-bd14-80ebaa2f7f9c
tags: []
