slice_name: k8s.pod.mem.total.requested.history
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 13__table
  viz_type: echarts_timeseries_line
  x_axis: _time
  time_grain_sqla: null
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: _value
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 59
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: FLOAT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: MAX
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: MAX(_value)
    optionName: metric_gqos288ds3u_jwae59owvz
  groupby:
  - cluster_name
  adhoc_filters:
  - clause: WHERE
    subject: _time
    operator: TEMPORAL_RANGE
    comparator: "24 hours ago : now"
    expressionType: SIMPLE
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title: GiB
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  currency_format: {}
  truncateXAxis: true
  extra_form_data: {}
  dashboards:
  - 2
  order_desc: false
query_context: '{"datasource":{"id":13,"type":"table"},"force":false,"queries":[{"filters":[{"col":"_time","op":"TEMPORAL_RANGE","val":"24 hours ago : now"}],"extras":{"time_grain_sqla":null,"having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":null,"columnType":"BASE_AXIS","sqlExpression":"_time","label":"_time","expressionType":"SQL"},"cluster_name"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"_value","description":null,"expression":null,"filterable":true,"groupby":true,"id":59,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"MAX","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"MAX(_value)","optionName":"metric_gqos288ds3u_jwae59owvz"}],"orderby":[],"annotation_layers":[],"row_limit":10000,"series_columns":["cluster_name"],"series_limit":0,"order_desc":false,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["_time"],"columns":["cluster_name"],"aggregates":{"MAX(_value)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"13__table","viz_type":"echarts_timeseries_line","x_axis":"_time","time_grain_sqla":null,"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"_value","description":null,"expression":null,"filterable":true,"groupby":true,"id":59,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"MAX","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"MAX(_value)","optionName":"metric_gqos288ds3u_jwae59owvz"}],"groupby":["cluster_name"],"adhoc_filters":[{"clause":"WHERE","subject":"_time","operator":"TEMPORAL_RANGE","comparator":"24 hours ago : now","expressionType":"SIMPLE"}],"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title":"GiB","y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","seriesType":"line","show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","currency_format":{},"truncateXAxis":true,"extra_form_data":{},"dashboards":[2],"force":false,"result_format":"json","result_type":"full","order_desc":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 68b6665c-74ef-49ac-b4b7-cda87f137dbd
version: 1.0.0
dataset_uuid: b9e5bfa1-3159-477f-b5d2-be3bcd7539cb
tags: []
